# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train:  D:/work-wyz/yolov5-pro/number/images/
val:  D:/work-wyz/yolov5-pro/number/images/
# number of classes
nc: 10

# class names
names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
