# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train:  ./images/
val:  ./images/
# number of classes
nc: 3

# class names
names: ['1 class1', '2 class2', '3 class3']