# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train:  D:/work-wyz/FarmSense/yolov5-pro/doraemon/images/
val:  D:/work-wyz/FarmSense/yolov5-pro/doraemon/images/
# number of classes
nc: 1

# class names
names: ['doraemon']
